Big refactor of SOFTWARE-INSTALLER. (more in detailed description)
* Implemented partial software installation
* Done marking requirement installation. Each definition requirement is now marked as installed.
* Implemented "one" app installer mode which enables user owned applications installed directly into user home dir (Into ~/Apps)

Signed-off-by: Daniel (dmilith) Dettlaff <dmilith@verknowsys.com>

diff --git a/SOFTWARE-INSTALLER b/SOFTWARE-INSTALLER
--- a/SOFTWARE-INSTALLER
+++ b/SOFTWARE-INSTALLER
@@ -1,22 +1,28 @@
 #!/bin/sh
 
+
 unset LDFLAGS
 unset CFLAGS
 unset CPPFLAGS
+unset PATH
+unset LD_LIBRARY_PATH
+unset LD_PRELOAD
 
-if [ ! -e $(pwd)/config ]; then
-    error "Unable to find config: $(pwd)/config"
+
+# cloading config
+if [ ! -e "lib/config" ]; then
+    echo "# Unable to find config: lib/config"
     exit
 fi
-. $(pwd)/config
+. "lib/config"
 
 
-check_root () {
-    if [ ! "$($ID_BIN -u)" = "0" ]; then
-        error "This command should be run as root in current stage."
-        exit
-    fi
-}
+# cloading helpers
+if [ ! -e "lib/helpers" ]; then
+    echo "# Unable to find helpers: lib/helpers"
+    exit
+fi
+. "lib/helpers"
 
 
 check_command_result () {
@@ -29,7 +35,7 @@ check_command_result () {
     else
         error
         error "FAILURE! --------------> Last log:"
-        $TAIL_BIN -n 20 $LOG
+        $TAIL_BIN -n 50 $LOG
         exit
     fi
 }
@@ -59,7 +65,7 @@ check_requirements () {
 
 usage_howto () {
     error "No task param given!"
-    error "Built in tasks: list, destroyall, getshellpath, getshellld, custom-definition-list-file"
+    error "Built in tasks: list, destroyall, getshellpath, getshellld, one, custom-definition-list-file"
     exit
 }
 
@@ -93,13 +99,13 @@ if [ ! "$1" = "" ]; then
         for app in $SOFTWARE_DIR*; do
             if [ -L $app ]; then
                 if [ -e "${app}/bin" ]; then
-                    result="${app}/bin:$result"
+                    result="${result}:${app}/bin"
                 fi
                 if [ -e "${app}/sbin" ]; then
-                    result="${app}/sbin:$result"
+                    result="${result}:${app}/sbin"
                 fi
                 if [ -e "${app}/libexec" ]; then
-                    result="${app}/libexec:$result"
+                    result="${result}:${app}/libexec"
                 fi
             fi
         done
@@ -125,10 +131,27 @@ if [ ! "$1" = "" ]; then
         exit
         ;;
 
+    one)
+        if [ "$2" = "" ]; then
+            error "For \"one\" application installation mode, second argument with UID is required!"
+            exit 1
+        fi
+        if [ "$3" = "" ]; then
+            error "For \"one\" application installation mode, third argument with Application def file name (without extension) is required!"
+            exit 1
+        fi
+        
+        note "One app installation mode for given UID: $2 of definition: $3 on the way…"
+        export APPLICATIONS="$3"
+        export UID="$2"
+        note "Parsing definition: $APPLICATIONS"
+
+        ;;
+        
     *)
         if [ ! -e $1 ]; then
             error "Definition not found: $1"
-            exit
+            exit 1
         fi
         export APPLICATIONS="$($CAT_BIN $1 | $TR_BIN '\n' ' ')"
         note "Parsing definitions: $APPLICATIONS"
@@ -140,9 +163,10 @@ else
 fi
 
 
+#---------------------------------------------------------------------------
+
 
 check_requirements
-check_root
 
 for application in $APPLICATIONS; do
 
@@ -156,169 +180,201 @@ for application in $APPLICATIONS; do
         note
         note "Preparing application: ${APP_NAME} (${APP_FULL_NAME})"
         if [ -z $APP_POSTFIX ]; then
-            export PREFIX=${SOFTWARE_DIR}${APP_NAME}-${APP_VERSION}
+            if [ $UID = "" ]; then
+                export PREFIX="${SOFTWARE_DIR}${APP_NAME}-${APP_VERSION}"
+            else
+                export PREFIX="${HOME_DIR}${UID}/${HOME_APPS_DIR}${APP_NAME}"
+            fi
         else
-            export PREFIX=${SOFTWARE_DIR}${APP_NAME}-${APP_VERSION}-${APP_POSTFIX}
+            if [ $UID = "" ]; then
+                export PREFIX=${SOFTWARE_DIR}${APP_NAME}-${APP_VERSION}-${APP_POSTFIX}
+            else
+                export PREFIX="${HOME_DIR}${UID}/${HOME_APPS_DIR}${APP_NAME}${APP_POSTFIX}"
+            fi
         fi
 
-        if [ -e $PREFIX ]; then
-            note "Application already installed in $PREFIX."
-        else
-            run () {
-                if [ ! -z "$1" ]; then
-                    export PATH="$PREFIX/bin:$PREFIX/sbin:$DEFAULT_PATH"
-                    export LD_LIBRARY_PATH="$PREFIX/lib:$PREFIX/libexec"
-                    debug "PATH: $PATH" >> $LOG
-                    debug "CXXFLAGS: $CXXFLAGS" >> $LOG
-                    debug "CFLAGS: $CFLAGS" >> $LOG
-                    debug "LDFLAGS: $LDFLAGS" >> $LOG
-                    debug "LD_LIBRARY_PATH: $LD_LIBRARY_PATH" >> $LOG
-                    debug "Current DIR: $BUILD_DIR$dir" >> $LOG
-                    definition_dir_check
-                    if [ ! -e "$LOG" ]; then
-                        $TOUCH_BIN "$LOG"
+        run () {
+            if [ ! -z "$1" ]; then
+                export PATH="$PREFIX/bin:$PREFIX/sbin:$DEFAULT_PATH"
+                export LD_LIBRARY_PATH="$PREFIX/lib:$PREFIX/libexec"
+                debug "PATH: $PATH" >> $LOG
+                debug "CXXFLAGS: $CXXFLAGS" >> $LOG
+                debug "CFLAGS: $CFLAGS" >> $LOG
+                debug "LDFLAGS: $LDFLAGS" >> $LOG
+                debug "LD_LIBRARY_PATH: $LD_LIBRARY_PATH" >> $LOG
+                debug "Current DIR: $BUILD_DIR$dir" >> $LOG
+                definition_dir_check
+                if [ ! -e "$LOG" ]; then
+                    $TOUCH_BIN "$LOG"
+                fi
+                debug "Running '$@' @ `$DATE_BIN`" >> "$LOG"
+                eval PATH=$PATH "$@" 1>> "$LOG" 2>> "$LOG"
+                check_command_result $?
+            else
+                error "Empty command to run?"
+                exit
+            fi
+        }
+
+        execute_process () {
+            if [ -z "$1" ]; then
+                error "No param given for execute_process()!"
+                exit
+            fi
+            req_definition_file="$DEFINITIONS_DIR$1.def"
+            debug "Checking requirement: $1 file: $req_definition_file"
+            if [ ! -e $req_definition_file ]; then
+                error "Definition file for requirement: '$1' does not exists!"
+                exit
+            fi
+            . $DEFAULTS
+            . $req_definition_file
+            export ALLOW=1
+            if [ ! "$DISABLE_ON" = "" ]; then
+                for disabled in $DISABLE_ON; do
+                    debug "Running system: $SYSTEM_NAME"
+                    debug "DisableOn element: $disabled"
+                    if [ "$SYSTEM_NAME" = "$disabled" ]; then
+                        export ALLOW=0
                     fi
-                    debug "Running '$@' @ `$DATE_BIN`" >> "$LOG"
-                    eval PATH=$PATH "$@" 1>> "$LOG" 2>> "$LOG"
-                    check_command_result $?
+                done
+            fi
+
+            if [ "$ALLOW" = "1" ]; then
+                if [ -z "$APP_HTTP_PATH" ]; then
+                    debug "After install callback: $APP_AFTER_INSTALL_CALLBACK"
+                    run $APP_AFTER_INSTALL_CALLBACK
                 else
-                    error "Empty command to run?"
-                    exit
-                fi
-            }
-            execute_process () {
-                if [ -z "$1" ]; then
-                    error "No param given for execute_process()!"
-                    exit
-                fi
-                req_definition_file="$DEFINITIONS_DIR$1.def"
-                debug "Checking requirement: $1 file: $req_definition_file"
-                if [ ! -e $req_definition_file ]; then
-                    error "Definition file for requirement: '$1' does not exists!"
-                    exit
-                fi
-                . $DEFAULTS
-                . $req_definition_file
-                export ALLOW=1
-                if [ ! "$DISABLE_ON" = "" ]; then
-                    for disabled in $DISABLE_ON; do
-                        debug "Running system: $SYSTEM_NAME"
-                        debug "DisableOn element: $disabled"
-                        if [ "$SYSTEM_NAME" = "$disabled" ]; then
-                            export ALLOW=0
+                    BUILD_DIR="$TMP_ROOT$APP_NAME-$APP_VERSION/"
+                    $MKDIR_BIN -p "$BUILD_DIR"
+                    CUR_DIR=$(pwd)
+                    cd "$BUILD_DIR"
+                    for bd in $BUILD_DIR/*; do
+                        if [ -d $bd ]; then
+                            debug "Unpacked source code found in build dir. Removing: $bd"
+                            $RM_BIN -rf $bd
                         fi
                     done
-                fi
-
-                if [ "$ALLOW" = "1" ]; then
-                    if [ -z "$APP_HTTP_PATH" ]; then
-                        debug "After install callback: $APP_AFTER_INSTALL_CALLBACK"
-                        run $APP_AFTER_INSTALL_CALLBACK
+                    if [ ! -e $BUILD_DIR$1*tar.gz ]; then
+                        note "Fetching requirement source from: $APP_HTTP_PATH"
+                        run $FETCH_BIN $APP_HTTP_PATH
                     else
-                        BUILD_DIR="$TMP_ROOT$APP_NAME-$APP_VERSION/"
-                        $MKDIR_BIN -p "$BUILD_DIR"
-                        CUR_DIR=$(pwd)
-                        cd "$BUILD_DIR"
-                        for bd in $BUILD_DIR/*; do
-                            if [ -d $bd ]; then
-                                debug "Unpacked source code found in build dir. Removing: $bd"
-                                $RM_BIN -rf $bd
-                            fi
-                        done
-                        if [ ! -e $BUILD_DIR$1*tar.gz ]; then
-                            note "Fetching requirement source from: $APP_HTTP_PATH"
-                            run $FETCH_BIN $APP_HTTP_PATH
-                        else
-                            debug "Already fetched. Using tarball from cache"
-                        fi
-                        note "Unpacking source code of: $APP_NAME"
-                        run $TAR_BIN xf $BUILD_DIR$APP_NAME*
-                        debug "Entrering $BUILD_DIR$APP_NAME*" >> $LOG
-                        for dir in `$LS_BIN -F $BUILD_DIR | $GREP_BIN \/$`; do
-                            debug "Changing dir to: $dir" >> $LOG
-                            cd "$dir$APP_SOURCE_DIR_POSTFIX"
-                            export CXXFLAGS="-I${PREFIX}/include $APP_COMPILER_ARGS"
-                            export CFLAGS="-I${PREFIX}/include $APP_COMPILER_ARGS"
-                            export LDFLAGS="-L${PREFIX}/lib $APP_LINKER_ARGS"
-                            LIST_DIR=${DEFINITIONS_DIR}patches/$1
-                            if [ -d $LIST_DIR ]; then
-                                if [ "$1" = "$APP_NAME" ]; then # apply patch only when application/requirement for which patch is designed for
-                                    debug "Applying patches for application: $application"
-                                    for patch in $LIST_DIR/*; do
-                                        debug "Patching source code with patch: $patch"
-                                        run $PATCH_BIN -i "$patch"
-                                    done
-                                fi
-                            fi
-
-                            debug "Running configuration script for: $1 with args: --prefix=$PREFIX $APP_CONFIGURE_ARGS"
-                            note "Configuring requirement: $1"
-                            case $APP_CONFIGURE_SCRIPT in
-                                ignore)
-                                    note "Ignored configuration part $1"
-                                    ;;
-                                    
-                                no-conf)
-                                    note "Skipped configuration for $1"
-                                    export APP_MAKE_METHOD="$APP_MAKE_METHOD PREFIX=$PREFIX"
-                                    export APP_INSTALL_METHOD="$APP_INSTALL_METHOD PREFIX=$PREFIX"
-                                    ;;
-
-                                binary)
-                                    note "Binary definition: $1"
-                                    export APP_MAKE_METHOD="true"
-                                    export APP_INSTALL_METHOD="true"
-                                    ;;
-
-                                cmake)
-                                    run ${APP_CONFIGURE_SCRIPT} . -LH -DCMAKE_INSTALL_PREFIX=$PREFIX
-                                    ;;
-
-                                *)
-                                    run ${APP_CONFIGURE_SCRIPT} ${APP_CONFIGURE_ARGS} --prefix=$PREFIX
-                                    ;;
-
-                            esac
-
-                            note "Building requirement: $1"
-                            run "$APP_MAKE_METHOD"
-                            note "Installing requirement: $1"
-                            run "$APP_INSTALL_METHOD"
-                            if [ ! "$APP_AFTER_INSTALL_CALLBACK" = "" ]; then
-                                debug "After install callback: $APP_AFTER_INSTALL_CALLBACK"
-                                run "$APP_AFTER_INSTALL_CALLBACK"
-                            fi
-                            note "Installed '$1' in: $PREFIX"
-                        done
-                        cd $CUR_DIR
+                        debug "Already fetched. Using tarball from cache"
                     fi
-                else
-                    note "This bundle is disabled on current architecture ($SYSTEM_NAME). Skipped"
+                    note "Unpacking source code of: $APP_NAME"
+                    run $TAR_BIN xf $BUILD_DIR$APP_NAME*
+                    debug "Entrering $BUILD_DIR$APP_NAME*" >> $LOG
+                    for dir in `$LS_BIN -F $BUILD_DIR | $GREP_BIN \/$`; do
+                        debug "Changing dir to: $dir" >> $LOG
+                        cd "$dir$APP_SOURCE_DIR_POSTFIX"
+                        export CXXFLAGS="-I${PREFIX}/include $APP_COMPILER_ARGS"
+                        export CFLAGS="-I${PREFIX}/include $APP_COMPILER_ARGS"
+                        export LDFLAGS="-L${PREFIX}/lib $APP_LINKER_ARGS"
+                        LIST_DIR=${DEFINITIONS_DIR}patches/$1
+                        if [ -d $LIST_DIR ]; then
+                            if [ "$1" = "$APP_NAME" ]; then # apply patch only when application/requirement for which patch is designed for
+                                note "Applying patches for application: $application"
+                                for patch in $LIST_DIR/*; do
+                                    debug "Patching source code with patch: $patch"
+                                    run $PATCH_BIN -i "$patch"
+                                done
+                            fi
+                        fi
+
+                        debug "Running configuration script for: $1"
+                        note "Configuring requirement: $1"
+                        case $APP_CONFIGURE_SCRIPT in
+                            ignore)
+                                note "Ignored configuration part $1"
+                                ;;
+                                    
+                            no-conf)
+                                note "Skipped configuration for $1"
+                                export APP_MAKE_METHOD="$APP_MAKE_METHOD PREFIX=$PREFIX"
+                                export APP_INSTALL_METHOD="$APP_INSTALL_METHOD PREFIX=$PREFIX"
+                                ;;
+
+                            binary)
+                                note "Binary definition: $1"
+                                export APP_MAKE_METHOD="true"
+                                export APP_INSTALL_METHOD="true"
+                                ;;
+
+                            cmake)
+                                run ${APP_CONFIGURE_SCRIPT} . -LH -DCMAKE_INSTALL_PREFIX=$PREFIX
+                                ;;
+
+                            *)
+                                run ${APP_CONFIGURE_SCRIPT} ${APP_CONFIGURE_ARGS} --prefix=$PREFIX
+                                ;;
+
+                        esac
+
+                        note "Building requirement: $1"
+                        run "$APP_MAKE_METHOD"
+                        note "Installing requirement: $1"
+                        run "$APP_INSTALL_METHOD"
+                        if [ ! "$APP_AFTER_INSTALL_CALLBACK" = "" ]; then
+                            debug "After install callback: $APP_AFTER_INSTALL_CALLBACK"
+                            run "$APP_AFTER_INSTALL_CALLBACK"
+                        fi
+                        note "Marking installed '$1' in: $PREFIX"
+                        $TOUCH_BIN "$PREFIX/$1.INSTALLED"
+                    done
+                    cd $CUR_DIR
                 fi
-            }
+            else
+                note "This bundle is disabled on current architecture ($SYSTEM_NAME). Skipped"
+            fi
+        }
 
-            debug "App Requirements: $APP_REQUIREMENTS"
-            for req in $APP_REQUIREMENTS; do
-                note "Configuring requirement: $req"
+        debug "App Requirements: $APP_REQUIREMENTS"
+        for req in $APP_REQUIREMENTS; do
+            note "Configuring requirement: $req"
+            if [ -e "$PREFIX/$req.INSTALLED" ]; then
+                note "Requirement: $req marked as installed. Skipping…"
+            else
+                export CHANGED="true"
                 execute_process $req
-            done
-            execute_process $application
+            fi
+        done
 
+        if [ -e "$PREFIX/$application.INSTALLED" ]; then
+            if [ "$CHANGED" = "true" ]; then
+                note "At least one of app dependencies has been changed. Forced rebuild of application…"
+                execute_process $application
+                unset CHANGED
+            else
+                note "Requirement: $application marked as installed. Skipping…"
+            fi
+        else
+            execute_process $application
+        fi
+
+        # make symlink to current version of software only when building relocatable application:
+        if [ "$UID" = "" ]; then
             # making app symlink to current version of given app
             req_definition_file="$DEFINITIONS_DIR$application.def"
             . $DEFAULTS
             . $req_definition_file
             APP_NAME="$(echo "$APP_NAME" | $CUT_BIN -c1 | $TR_BIN '[a-z]' '[A-Z]')$(echo "$APP_NAME" | $SED_BIN 's/^[a-zA-Z]//')"
             if [ -z $APP_POSTFIX ]; then
-                export PREFIX=$SOFTWARE_DIR$APP_NAME-$APP_VERSION
+                export PREFIX="${SOFTWARE_DIR}${APP_NAME}-${APP_VERSION}"
             else
-                export PREFIX=$SOFTWARE_DIR$APP_NAME-$APP_VERSION-$APP_POSTFIX
+                export PREFIX=${SOFTWARE_DIR}${APP_NAME}-${APP_VERSION}-${APP_POSTFIX}
             fi
             note "Removing current symlink to latest version of $APP_NAME"
             $RM_BIN -f $SOFTWARE_DIR$APP_NAME
             note "Making symlink to latest version of $APP_NAME pointing to $SOFTWARE_DIR$APP_NAME"
             $LN_BIN -s $PREFIX $SOFTWARE_DIR$APP_NAME
-
+        fi
+            
+        note "Marking definition: $application installed"
+        $TOUCH_BIN "$PREFIX/$application.INSTALLED"
+            
+        if [ ! "$UID" = "" ]; then
+            note "Setting owner of $PREFIX to UID: $UID"
+            $CHOWN_BIN -R $UID "$PREFIX"
         fi
 
     done
